version: '3'

services:
  backend:
    build: ./backEnd
    ports:
      - "3033:3001"

  frontend:
    build: ./frontEnd
    ports:
      - "8080:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27018:27017"
