version: '3'

services:
  backend:
    build: ./backEnd
    ports:
      - "3000:3000"

  frontend:
    build: ./frontEnd
    ports:
      - "80:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
